function sweep = get_sine_sweep_legacy(f1, f2, Ti, sil, fs)
%GET_SINE_SWEEP_LEGACY  Bit-faithful replica of the ORIGINAL Python ESS.
%   sweep = AMS.GET_SINE_SWEEP_LEGACY(f1, f2, Ti, sil, fs)
%
%   Reproduces get_sine_sweep() from utils_master.py EXACTLY, including its
%   quirks, so recordings of sweeps generated by that Python code can be
%   deconvolved with a matching inverse filter. Differences from the
%   corrected AMS.GET_SINE_SWEEP:
%
%     * L is ROUNDED to an integer:  L = round(Ti*f1/log(f2/f1))
%     * the phase uses the original (buggy) grouping:
%           sweep = sin( 2*pi*L*exp(f1*t/L) - 1 )
%       i.e. the "-1" sits outside the amplitude term (a constant phase
%       offset) rather than inside as (exp(...) - 1). The rounding of L also
%       makes the end frequency slightly overshoot f2.
%
%   Use this (with AMS.GET_INVERSE_FILTER_LEGACY, via MEASURE_IR's Legacy
%   option) for the ESS5S / ESS3S recordings, which were made with the
%   original Python generator (f1=20, f2=20000, sil=0). For sweeps made with
%   this project's gen_sine.m / AMS.GET_SINE_SWEEP, use the corrected version.

    f_in = 0.1; f_out = 0.1;                 % fade durations [s]
    N = round(Ti * fs);
    t = (0:N-1).' / fs;

    L = round(Ti * f1 / log(f2/f1));         % integer, as in the Python
    sweep = sin(2*pi*L * exp(f1*t/L) - 1);   % original (buggy) phase grouping

    ni = floor(f_in  * fs);                  % int() truncates in Python
    no = floor(f_out * fs);
    sweep(1:ni)         = sweep(1:ni)         .* linspace(0,1,ni).';
    sweep(end-no+1:end) = sweep(end-no+1:end) .* linspace(1,0,no).';

    sweep = [sweep; zeros(round(sil*fs),1)];
end
